import Head from 'next/head';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { GetStaticProps } from 'next';
import { useTranslation } from 'next-i18next';
import Hero from '@/components/hero';
import About from '@/components/about';
import Services from '@/components/services';
// import Partners from '@/components/partners';
import Interstitial from '@/components/interstitial';
import QuoteForm from '@/components/quote-form';
import ContactDetails from '@/components/contact-details';
import Footer from '@/components/layout/footer';

export default function Home() {
  const { t } = useTranslation('common');
  return (
    <>
      <Head>
        <title>Bayber</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <About />
      <Services />
      {/* <Partners /> */}
      <Interstitial />
      <QuoteForm />
      <ContactDetails />
      <Footer />
    </>
  );
}

export const getStaticProps: GetStaticProps = async ({ locale }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale!, ['common', 'footer'])),
    },
  };
};
