import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Bayber</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* HEADER */}

      {/* MAIN */}
      <main>
        {/* HERO */}
        {/* ABOUT */}
        {/* SERVICES */}
        {/* PARTNERS */}
        {/* CONTACT */}
      </main>

      {/* FOOTER */}
    </>
  );
}
