import Head from 'next/head';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { GetStaticProps } from 'next';
import { useTranslation } from 'next-i18next';
import Hero from '@/components/hero';
import About from '@/components/about';
import Services from '@/components/services';

export default function Home() {
  const { t } = useTranslation('common');
  return (
    <>
      <Head>
        <title>Bayber</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <About />
      <Services />
      {/* PARTNERS */}
      {/* CONTACT */}

      {/* FOOTER */}
    </>
  );
}

export const getStaticProps: GetStaticProps = async ({ locale }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale!, ['common', 'footer'])),
    },
  };
};
